services:

  pa_endpoint.loader:
    class: PaLabs\EndpointBundle\Loader\EndpointRouteLoader
    tags:
      - {name: 'routing.loader'}

  pa_endpoint.cache_warmer:
    class: PaLabs\EndpointBundle\Cache\EndpointRouteCacheWarmer
    tags:
      - {name: 'kernel.cache_warmer'}

  pa_endpoint.route_generator:
    class: AppBundle\System\Component\Endpoint\EndpointRouteGenerator
    arguments:
      - '@router'
      - '%kernel.cache_dir%'
